version: '3.8'

services:
    caddy:
        build: .
        restart: unless-stopped
        deploy:
            placement:
                constraints:
                    - node.role == manager
            replicas: 1
            restart_policy:
                condition: any
            resources:
                reservations:
                    cpus: "0.1"
                    memory: "100M"
                limits:
                    cpus: "0.5"
                    memory: "500M"
            update_config:
                parallelism: 2
                delay: 5s
                order: stop-first
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./caddy:/etc/caddy
            - caddy_data:/data
            - caddy_config:/config
            #- "/var/www/html:/var/www/html"
        networks:
            - core_net

volumes:
    caddy_data:
    caddy_config:

networks:
    core_net: